### ISSUE TITLE
Segfault on 0.9.17.3-1

### ISSUE THREAD

**Issue by gheinrich** [shmul/lightningmdb#10]
Hello and thanks for making this project available! I am using this library quite heavily in [DIGITS](https://github.com/NVIDIA/DIGITS).
We are installing the library through this command:
```
luarocks install lightningmdb LMDB_INCDIR=/usr/include LMDB_LIBDIR=/usr/lib/x86_64-linux-gnu
```
Yesterday our automatic scripts picked up a regression ([see](https://github.com/NVIDIA/DIGITS/pull/541#issuecomment-174752814)).

On my local setup I used to have version `0.9.17-1` and this was working fine. If I run the `luarocks install lightningmdb` command again then Luarocks fetches version `0.9.17.3-1` which causes a systematic segfault.

If I download the top of the `master` branch on Github then version `0.9.17.4-1` which seems to be working well.

Question: is there any known regression in `0.9.17.3-1`? Can the Luarocks registry be updated to install `0.9.17.4-1` by default?

Thanks!

**Comment by lukeyeager** [comment]
Looks like this is the only relevant commit between the two versions: https://github.com/shmul/lightningmdb/commit/73fa91af7f7b22d687514321b32a26a159fae10e.

https://github.com/shmul/lightningmdb/compare/0.9.17.3-1...0.9.17.4-1

**Comment by shmul** [comment]
Hi,

Sorry for the late response, just noticed this now. I'm happy to see the library usefulness :)

I was working on supporting Lua 5.3 and had a lot of intermediate (and unstable so it seems) versions of the rock uploaded during my tests. Some were indeed broken, but as far as I know, 0.9.17.4-1 solves them all. I uploaded it to the main luarocks site a couple of days ago and it is listed there now.

So, are you still experiencing problems?

I'm taking a note to myself, and will port some docker based tests to this project so I can easily and automatically pick up its faults across various Lua versions and OSs (I'm using a Mac, but need to test it on Linux also).

Cheers,
Shmul

**Comment by lukeyeager** [comment]
I just verified that the version from the main luarocks site works. Thanks for uploading it!

https://travis-ci.org/lukeyeager/DIGITS/builds/106273860
