### ISSUE TITLE
Possible regression in 0.9.18.2-1

### ISSUE THREAD

**Issue by gheinrich** [shmul/lightningmdb#13]
Hello, I am now seeing this error when loading lightningmdb:
```
/home/travis/torch/install/lib/lua/5.1/lightningmdb.so: undefined symbol: mdb_txn_id
```

See https://github.com/NVIDIA/DIGITS/issues/908#issuecomment-233049523

Is this related to version 0.9.18.2-1? Note that version 0.9.18.1-1 seems to be working fine. I am using Ubuntu and liblmdb-dev version 0.9.10-1.

**Comment by lukeyeager** [comment]
I have a hypothesis.

It looks like these lines in the Makefile:
https://github.com/shmul/lightningmdb/blob/0.9.18.2-1/Makefile#L10-L11

may overwite the values set in the rockspec:
https://github.com/shmul/lightningmdb/blob/0.9.18.2-1/lightningmdb-0.9.18.2-1.rockspec#L31-L32

Which would explain the regression, since https://github.com/shmul/lightningmdb/commit/184f3788809e68c897a6b2def34a5e9377278fa8 was added in the latest release.

**Comment by shmul** [comment]
I'll make some time during the weekend to fix this. In the meantime, can you please tell me which Lua version are you using?
Please note that you can safely revert to the previous version. There was no functionality added, just some fixes around the handling of the Lua stack. It works for me with 5.3.3 but apparently not for all.

Cheers,
Shmul

**Comment by gheinrich** [comment]
Thanks @shmul I am using Lua 5.1.

**Comment by shmul** [comment]
An update - I pushed a [`docker_build_images`](https://github.com/shmul/lightningmdb/tree/docker_build_images) branch, which ported the docker images from [mule](https://github.com/shmul/mule) (`lightningmdb`'s _parent_ project; thanks @dubek) . Simply run `./docker/build_container.sh lua5.1` to test the build process per Lua version (try 5.2 and 5.3 also if you want).

Everything builds just fine, though on Ubuntu the include path is different from my Mac one, hence the `make` invocation specify them explicitly (e.g. check out the last line of `docker/Dockerfile-lua5.1`). I suspect that this might be a hint towards solving the problem you are experiencing. 

Can it be that there are multiple Lua installations or LMDB installations on the machine you are building on?

**Comment by gheinrich** [comment]
Hi @shmul I am sorry about the late response. I am using  liblmdb-dev version 0.9.10-1, which seems to be the default on Ubuntu 14.04. If I patch your Dockerfile this way:
```
-ENV lmdb_ver 0.9.18
+ENV lmdb_ver 0.9.10
```
Then I get this error when running the `./docker/build_container.sh lua5.1` script:
```
 ---> Running in a64d145ff951
cc -I/usr/include/lua5.1 -I/usr/local/include -pedantic -Wall  -g -O2 -fPIC -DUSE_GLOBALS   -c -o lightningmdb.o lightningmdb.c
lightningmdb.c: In function 'txn_id':
lightningmdb.c:540:21: warning: implicit declaration of function 'mdb_txn_id' [-Wimplicit-function-declaration]
   lua_pushinteger(L,mdb_txn_id(txn));
                     ^
cc -o lightningmdb.so -shared lightningmdb.o -I/usr/include/lua5.1 -I/usr/local/include -pedantic -Wall  -g -O2 -fPIC -DUSE_GLOBALS -L/usr/lib -L/usr/local/lib -llmdb 
/usr/bin/lua test.lua
/usr/bin/lua: error loading module 'lightningmdb' from file './lightningmdb.so':
	./lightningmdb.so: undefined symbol: mdb_txn_id
stack traceback:
	[C]: ?
	[C]: in function 'require'
	./test_common.lua:1: in main chunk
	[C]: in function 'require'
	test.lua:1: in main chunk
	[C]: ?
make: *** [test] Error 1
```

**Comment by shmul** [comment]
Hi,

It seems mdb_txn_id is not supported by 0.9.10. Can you update your
installation to a more recent version?

**Comment by gheinrich** [comment]
Thanks for the feedback. Upgrading LMDB is an option through since Ubuntu 14.04 comes with LMDB 0.9.10 by default I think I'd rather stick to a version of the Lua wrappers that works against this library.

**Comment by gheinrich** [comment]
Besides, I think Ubuntu 16.04 comes with LMDB 0.9.17-3 by default. It might take a while until version 0.9.18 becomes widespread. Which version of shmul/lightningmdb would you recommend we use? Thanks!

**Comment by lukeyeager** [comment]
Agreed. We won't be asking our users to build LMDB from source. We're willing to pin an old version of `lightningmdb` if necessary.

**Comment by gheinrich** [comment]
Hi @shmul we have decided to pin version 0.9.18.1-1. I'll close this issue. Thanks!
