### ISSUE TITLE
LuaRocks

### ISSUE THREAD

**Issue by catwell** [shmul/lightningmdb#3]
Hello, this module is not available in LuaRocks. Could you write a rockspec for it and push it to MoonRocks? Do you need help with this?

**Comment by shmul** [comment]
Hi,

I'll try to write one and will probably ask for your help in verifying that
it works on your system.

Cheers,
Shmul

**Comment by shmul** [comment]
That was pretty easy. I pushed the rockspec (lightningmdb-0.9-1.rockspec).
Can you please test that it works on your system? Note the lmdb needs to be
installed (the instructions are in the readme file). The build command for
me was

luarocks --local make
LMDBINC=/home/shmul/dev/remotes/mdb/libraries/liblmdb/
LMDBLIB=/home/shmul/dev/remotes/mdb/libraries/liblmdb/

Let me know whether it worked for you.

Cheers,
Shmul

**Comment by catwell** [comment]
Hello, a bit of feedback.

The Git URL should be:

    git://github.com/shmul/lightningdbm.git

(the current URL only works for you)

Setting `LMDBINC` and `LMDBLIB` should not be mandatory if LMDB is installed in the system, i.e.:

    LMDBINC=/usr/include
    LMDBLIB=/usr/lib

I created a [pull request](https://github.com/shmul/lightningdbm/pull/4) that fixes these two things (had to rename `LMDBINC` and `LMDBLIB` to `LMDB_INCDIR` and `LMDB_LIBDIR`, see PR) as well as a small 5.2 compilation bug.

With those changes, I can trivially install the module using LuaRocks for both 5.1 and 5.2 on my system (Arch Linux):

    sudo luarocks-5.1 install lightningmdb-0.9-1.rockspec
    sudo luarocks-5.2 install lightningmdb-0.9-1.rockspec

**Comment by shmul** [comment]
Great. Thanks. I merged it.

I asked a couple of friends to test it on their systems and then I'll push
it to MoonRocks.

Cheers,
Shmul
